DELETE FROM Witnesses;

INSERT INTO Witnesses(BriefingID, Name, Occupation, Age, Gender, Statement)
VALUES(1, "Sarah Lockingham", "Software Engineer", 28, "Female", "The observatory normally has centralised heating, but I remember my teeth chattering the whole evening"),
	(1, "David Wicker", "Astronomer", 54, "Male", "My mum packed my lunch for me that day and someone ate it!"),
	(2, "Penguin", "Penguin", 3, "Male", "Quack! Quack! Quack!"),
	(2, "Polar Bear", "Polar Bear", 12, "Female", "Mrs Bear bit off the interviewer's hand, and smacked the recording camera to the ground. Our cryptographers are still attempting to decipher the message"),
	(3, "Erik Darkstone", "Fry Cook", 17, "Male", "I tried running away, I can’t afford my health insurance premiums going up anymore if I got hurt, but the lady rescuing the criminals was too damn awesome. One of the guys took my shoe."),
	(3, "Sonny Blair", "Forgerer", 22, "Other", "I didn’t see anything, I was just there to get my passport renewed."),
	(3, "Frankie Hare", "Not Given", 33, "Male", "Hello World"),
	(4, "Sophia Berkavich", "Bariester", 25, "Female", "I know they said disco’s dead, but this is ridiculous!"),
	(4, "Sonya Texas", "Influencer", 31, "Female", "I was filming my next tick tock video when I saw my own back up dancers had been replaced those freaks! They hit their marks so I fired my other dancers and gave the zombies part time at $12/hour. Can you believe they bit me at my offer!"),
	(4, "Hank Clyde", "Propane Salesman", 64, "Male", "I didn’t see much, I’ve learnt to run away from any kooky sci-fi fantasy nonsense I see"),
	(5, "Victor Diabolus", "Medical Researcher", 59, "Male", "It was mine to use as I saw fit"),
	(5, "Brennen Mulligan", "Waiter", 22, "Male", "I work at the cafe across the street, the heat from the fire was like looking into the gates of hell, I think I saw something fly away, but there was so much smoke"),
	(6, "Sarah Carson", "Entrepreneur", 37, "Female", "And he cut in the line!"),
	(6, "Jenny Pitchers", "Retired", 75, "Female", "It was too much o' them videogames that made 'im like this."),
	(6, "Caesar Everie", "Unemployed", 25, "Male", "It was so scary!"),
	(7, "Christine Fine", "Barista", 30, "Female", "It was freezing in there!"),
	(7, "Sharan Moore", "Bank Worker", 27, "Female", "I was at my desk when a gush of wind went past behind me. When I looked to see what it was I saw a glimpse of someone wearing a bright red top."),
	(7, "Martin Jones", "Metalsmith", 34, "Male", "I was going to the bank to manage my account when coins started flying everywhere. It didn't look random though, it was like someone was controlling them."),
	(7, "Johnny Smith", "Not Given", 25, "Male", "I was walking past the bank when I saw a big explosion from the second floor. When it happened, this guy on a hoverboard made a beeline for the entrance. Weird."),
	(8, "Brett Olay", "Salesman", 49, "Male", "Did you know feeding bread to birds makes their stomachs explode?"),
	(8, "Ash Waterson", "Unemployed", 23, "Male", "Those birds are secret government spy drones and Dr. Birdbrain is their pawn."),
	(8, "Caesar Everie", "Unemployed", 25, "Male", "It was so scary!"),
	(9, "Tim Johnson", "Cobbler", 65, "Male", "My grandson always helps me with that rip in space-time stuff."),
	(9, "Blake Vass", "Accountant", 25, "Male", "I hate these dumb taking over the world pranks. Someone could get hurt!"),
	(9, "Caesar Everie", "Unemployed", 25, "Male", "It was so scary!"),
    (10, "Anna Peeters", "Kitchen Staff", 44, "Female", "I don’t really know what happened… I was at the kitchen sink looking out the window when I felt a gush of wind go past me, but when I turned around there was nothing behind me. You know its funny? My brother in law went through something really similar in the past, back in 2000."),
    (10, "Andre Jacobs", "Data Analyst", 36, "Male", "I work in the lower basements, where we hold the data centers. I definitely saw someone out of the ordinary down there, a lot of the lights had been knocked out, so I didn’t get a good look at their face, but when they saw me they jumped out the window, out onto the cliff side. I didn’t see any bodies out on the rocks, so I figured they got away."),
    (10, "Randal Holden", "Castle Guard", 22, "Male", "Well - huff - I was tied up for most of the attack - phew - sorry, I’m a bit out of breath. I saw a big guy knocking out lots of the guards, a real intimidating guy. When he was fighting he left tonnes of dents and imprints on the castle floor and walls. When I came into work I saw a weird looking van out front too, it had a lot of satellite dishes on top of it. I figured it was a news crew coming to do a segment on the ball the royal family was throwing, but after tonight I’m not too sure."),
    (10, "Becca Flanders", "Royal Seamstress", 45, "Female", "I wasn't anywhere near the scene of the crime, I didn't see anything. If you'll excuse me, one of the guards lost their uniform, I need to make them another one"),
    (11, "Frank Horrigan", "Super Villain", 32, "Male", "So you got me, big deal, we still completed our objective. If that Randal Rat and his hacker friend hadn't double crossed us I would've taken out every last one of you. I'm not worried though, my team will have me out before your body hits the floor. *NOTE: AT THIS POINT FRANK HORRIGAN BROKE OUT OF HIS BONDS*"),
    (11, "Mara Papa", "Writer", 33, "Female", "I'm afraid there wasn't that much that I was able to see, I saw someone with this scary metallic mask burst in through the window on their flying skateboard, and went straight into the security room. Then all the lights went off. There was lots of commotion, but I couldn't see anything else."),
    (11, "Stephen Peeters", "Musician", 30, "Male", "I was at the musuem, trying to get inspiration for my next song, when the lights went out. I felt this big whoosh go by me and I got knocked down, never saw what it was though."),
    (12, "John O'Leary", "Priest", 62, "Male", "Good heavens!"),
	(13, "Esther Josephine", "Retired", 65, "Other", "Well I never!"),
    (13, "Teleah Brassman", "Musician", 30, "Other", "One of the sheep ran into me, striking me with its wool. It felt quite pleasant."),
	(13, "Brody Kody", "Unemployed", 27, "Other", "Gnarly.");