DELETE FROM Heroes;

INSERT INTO Heroes(Name, Abilities, Status, Cost)
VALUES
	("Disco Man", "Has a Discoball helmet, which allows for 360 vision. Blinding light can be shot from each surface on the ball.", "Active", 8000),
    ("Solaris", "Harnesses solar energy for flight, energy blasts, and enhanced strength.", "Active", 22000),
	("Frostbite", "Controls ice and cold, can create ice constructs and lower temperatures.", "Deceased", 18000),
	("Spectra", "Can manipulate light to create illusions and become invisible.", "Active", 15000),
	("Thunderclap", "Generates shockwaves and sonic booms with his claps.", "Retired", 17000),
	("Archer", "Uses a bow and arrow for long range attacks. Has an assortment of arrows that can be used from immobilising enemies, to knocking them out cold.", "Active", 3000),
	("Pyra", "Controls fire, can generate and project flames.", "Active", 6000),
	("Aquaheart", "Communicates with marine life, manipulates water.", "Active", 15000),
	("Mindwarp", "Powerful telepath with mind control and telekinesis.", "Retired", 23000),
	("Steelblade", "Has an indestructible metallic body and super strength.", "Deceased", 19000),
    ("Doomba", "A repurposed Roomba that can deliver strong EMP blasts. Doomba has sentience.", "Active", 5000),
	("Vortex", "Controls wind and creates powerful whirlwinds.", "Active", 16000),
	("Lumina", "Emits blinding light and can heal minor injuries.", "Retired", 14000),
	("Quake", "Creates and controls earthquakes and tremors.", "Active", 20000),
	("Mystic", "Wields ancient magic for spellcasting and enchantments.", "Active", 22000),
	("Titan", "Grows to giant size, increasing strength and durability.", "Deceased", 25000),
	("Nebula", "Manipulates cosmic energy and has limited flight.", "Active", 21000),
	("Echo", "Can duplicate sounds and voices, creating confusion.", "Active", 13000),
	("Phantom", "Passes through solid objects and becomes intangible.", "Retired", 16000),
	("Blaze", "Super speed and friction-generated flames.", "Active", 18000),
	("Crimson Wing", "Flight with razor-sharp wings and enhanced agility.", "Deceased", 17000),
    ("Reflex", "Superhuman reflexes and agility for close combat and evasive maneuvers.", "Active", 13000),
    ("PayBack", "Any energy that they're hit with can be absorbed, and sent back to where it came from. Works with physical and magical powers, a hero for all occasions.", "Active", 9000),
	("Bullseye", "Perfect aim with any projectile, making them a versatile marksman.", "Active", 18000),
	("Volt", "Controls and generates electricity. Can create EMP blasts, fire electrical attacks, and power electrical machinery.", "Active", 20000),
	("Absorption", "Absorbs energy and redirects it in powerful bursts, gains enhanced strength and durability", "Active", 28000),
	("Mirrorball", "Reflects and manipulates light for blinding flashes, invisibility, and illusions", "Active", 22000),
    ("Shadowstrike", "Master of stealth and shadow manipulation.", "Active", 14000),
    ("Galadin", "Can summon a sword, shield and full set of armour of hardened light.", "Retired", 5000),
    ("Sludgema", "Can turn themself into a puddle of goo.", "Active", 3000),
    ("Arachnid Bro", "Can sling webs from afar to immobilise enemies.", "Active", 9000),
    ("The Kidna", "Can sprout and fire spikes from his back.", "Retired", 8000),
    ("Prop", "Can morph into any inaminate object within reach and somehow move as that object.", "Active", 5000),
	("Mindshot", "Can enter the dreams of living things and take photos to bring back to the real world.", "Active", 7000),
	("Plum", "Can become purple.", "Active", 2000),
	("Vantern", "Summons a cursed lantern which plunges eveything in its range into a sphere of darkness, blinding anyone inside with everyone outside unable to see in.", "Active", 7000),
	("Ballet", "Charges a powerful kick that becomes more lethal the longer they sustain a pirouette before unleashing the kick. Dropping the pirouette resets the charge.", "Active", 5000),
	("Tempura Ballista", "Fires a spray of boiling hot oil and breading from an enchanted frying pan.", "Active", 12000),
    ("Time Warp", "Can slow down time, useful for catching villains with super speed.", "Active", 8000)
	;

